
version: 2

sources:
    - name: staging
      #For bigquery:
      database: flights-kaggle-project

      schema: flights_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: flights_external

models:
    - name: total_flights
  
